// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgEmpty) Reset()         { *m = MsgEmpty{} }
func (m *MsgEmpty) String() string { return proto.CompactTextString(m) }
func (*MsgEmpty) ProtoMessage()    {}
func (*MsgEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{0}
}

func (m *MsgEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgEmpty.Unmarshal(m, b)
}
func (m *MsgEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgEmpty.Marshal(b, m, deterministic)
}
func (m *MsgEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEmpty.Merge(m, src)
}
func (m *MsgEmpty) XXX_Size() int {
	return xxx_messageInfo_MsgEmpty.Size(m)
}
func (m *MsgEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEmpty proto.InternalMessageInfo

type MsgLog struct {
	Module               string   `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Loglevel             string   `protobuf:"bytes,2,opt,name=loglevel,proto3" json:"loglevel,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp            uint64   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgLog) Reset()         { *m = MsgLog{} }
func (m *MsgLog) String() string { return proto.CompactTextString(m) }
func (*MsgLog) ProtoMessage()    {}
func (*MsgLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{1}
}

func (m *MsgLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgLog.Unmarshal(m, b)
}
func (m *MsgLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgLog.Marshal(b, m, deterministic)
}
func (m *MsgLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLog.Merge(m, src)
}
func (m *MsgLog) XXX_Size() int {
	return xxx_messageInfo_MsgLog.Size(m)
}
func (m *MsgLog) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLog.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLog proto.InternalMessageInfo

func (m *MsgLog) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *MsgLog) GetLoglevel() string {
	if m != nil {
		return m.Loglevel
	}
	return ""
}

func (m *MsgLog) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MsgLog) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type MsgRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Ttl                  int64    `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Request              []byte   `protobuf:"bytes,6,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRequest) Reset()         { *m = MsgRequest{} }
func (m *MsgRequest) String() string { return proto.CompactTextString(m) }
func (*MsgRequest) ProtoMessage()    {}
func (*MsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{2}
}

func (m *MsgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRequest.Unmarshal(m, b)
}
func (m *MsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRequest.Marshal(b, m, deterministic)
}
func (m *MsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequest.Merge(m, src)
}
func (m *MsgRequest) XXX_Size() int {
	return xxx_messageInfo_MsgRequest.Size(m)
}
func (m *MsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequest proto.InternalMessageInfo

func (m *MsgRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *MsgRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *MsgRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MsgRequest) GetTtl() int64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *MsgRequest) GetRequest() []byte {
	if m != nil {
		return m.Request
	}
	return nil
}

type MsgResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Code                 int64    `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	Response             []byte   `protobuf:"bytes,6,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgResponse) Reset()         { *m = MsgResponse{} }
func (m *MsgResponse) String() string { return proto.CompactTextString(m) }
func (*MsgResponse) ProtoMessage()    {}
func (*MsgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{3}
}

func (m *MsgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgResponse.Unmarshal(m, b)
}
func (m *MsgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgResponse.Marshal(b, m, deterministic)
}
func (m *MsgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResponse.Merge(m, src)
}
func (m *MsgResponse) XXX_Size() int {
	return xxx_messageInfo_MsgResponse.Size(m)
}
func (m *MsgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResponse proto.InternalMessageInfo

func (m *MsgResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgResponse) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *MsgResponse) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *MsgResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MsgResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *MsgResponse) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgEmpty)(nil), "proto.MsgEmpty")
	proto.RegisterType((*MsgLog)(nil), "proto.MsgLog")
	proto.RegisterType((*MsgRequest)(nil), "proto.MsgRequest")
	proto.RegisterType((*MsgResponse)(nil), "proto.MsgResponse")
}

func init() { proto.RegisterFile("proto/message.proto", fileDescriptor_33f3a5e1293a7bcd) }

var fileDescriptor_33f3a5e1293a7bcd = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xb1, 0x4e, 0xfb, 0x30,
	0x10, 0xc6, 0xe5, 0x34, 0x4d, 0x9b, 0xfb, 0xff, 0x85, 0xe0, 0x90, 0x90, 0x55, 0x31, 0x44, 0x99,
	0x32, 0x15, 0x04, 0x33, 0x23, 0x1b, 0x95, 0x90, 0x79, 0x82, 0xd2, 0x1c, 0x56, 0x24, 0xbb, 0x0e,
	0xf1, 0xa5, 0x52, 0x37, 0x16, 0xde, 0x1b, 0xc5, 0x71, 0x5a, 0x1e, 0x80, 0xc9, 0xdf, 0x77, 0x77,
	0xf6, 0xef, 0xd3, 0x19, 0xae, 0xdb, 0xce, 0xb1, 0xbb, 0xb3, 0xe4, 0xfd, 0x56, 0xd3, 0x3a, 0x38,
	0x9c, 0x87, 0xa3, 0x04, 0x58, 0x6e, 0xbc, 0x7e, 0xb6, 0x2d, 0x1f, 0x4b, 0x86, 0x6c, 0xe3, 0xf5,
	0x8b, 0xd3, 0x78, 0x03, 0x99, 0x75, 0x75, 0x6f, 0x48, 0x8a, 0x42, 0x54, 0xb9, 0x8a, 0x0e, 0x57,
	0xb0, 0x34, 0x4e, 0x1b, 0x3a, 0x90, 0x91, 0x49, 0xe8, 0x9c, 0x3c, 0x4a, 0x58, 0x44, 0x82, 0x9c,
	0x85, 0xd6, 0x64, 0xf1, 0x16, 0x72, 0x6e, 0x2c, 0x79, 0xde, 0xda, 0x56, 0xa6, 0x85, 0xa8, 0x52,
	0x75, 0x2e, 0x94, 0x5f, 0x02, 0x60, 0xe3, 0xb5, 0xa2, 0xcf, 0x9e, 0x3c, 0xe3, 0x05, 0x24, 0x4d,
	0x1d, 0xb1, 0x49, 0x53, 0x23, 0x42, 0xfa, 0xd1, 0x39, 0x1b, 0x71, 0x41, 0x0f, 0x33, 0xec, 0x22,
	0x25, 0x61, 0x37, 0xcc, 0xf0, 0xb1, 0xa5, 0xf0, 0x76, 0xae, 0x82, 0xc6, 0x4b, 0x98, 0x31, 0x1b,
	0x39, 0x2f, 0x44, 0x35, 0x53, 0x83, 0x1c, 0x02, 0x76, 0x23, 0x44, 0x66, 0x85, 0xa8, 0xfe, 0xab,
	0xc9, 0x96, 0xdf, 0x02, 0xfe, 0x85, 0x08, 0xbe, 0x75, 0x7b, 0x4f, 0x7f, 0x96, 0x01, 0x21, 0xdd,
	0xb9, 0x9a, 0x62, 0x88, 0xa0, 0x87, 0x15, 0x76, 0x91, 0x13, 0x63, 0x9c, 0xfc, 0xc3, 0x13, 0xe4,
	0xaf, 0xa6, 0xd7, 0xcd, 0xfe, 0xed, 0xb0, 0xc3, 0x7b, 0x58, 0x4c, 0x3b, 0xb9, 0x1a, 0xff, 0x6c,
	0x7d, 0x5e, 0xd3, 0x0a, 0x7f, 0x97, 0xc6, 0xeb, 0xef, 0x59, 0x28, 0x3d, 0xfe, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xaa, 0x1b, 0x27, 0x80, 0xf0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PluginSvcClient is the client API for PluginSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PluginSvcClient interface {
	Request(ctx context.Context, in *MsgRequest, opts ...grpc.CallOption) (*MsgResponse, error)
}

type pluginSvcClient struct {
	cc *grpc.ClientConn
}

func NewPluginSvcClient(cc *grpc.ClientConn) PluginSvcClient {
	return &pluginSvcClient{cc}
}

func (c *pluginSvcClient) Request(ctx context.Context, in *MsgRequest, opts ...grpc.CallOption) (*MsgResponse, error) {
	out := new(MsgResponse)
	err := c.cc.Invoke(ctx, "/proto.PluginSvc/Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginSvcServer is the server API for PluginSvc service.
type PluginSvcServer interface {
	Request(context.Context, *MsgRequest) (*MsgResponse, error)
}

// UnimplementedPluginSvcServer can be embedded to have forward compatible implementations.
type UnimplementedPluginSvcServer struct {
}

func (*UnimplementedPluginSvcServer) Request(ctx context.Context, req *MsgRequest) (*MsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}

func RegisterPluginSvcServer(s *grpc.Server, srv PluginSvcServer) {
	s.RegisterService(&_PluginSvc_serviceDesc, srv)
}

func _PluginSvc_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginSvcServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PluginSvc/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginSvcServer).Request(ctx, req.(*MsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PluginSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PluginSvc",
	HandlerType: (*PluginSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _PluginSvc_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/message.proto",
}
